/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
    mavenCentral()
    maven { url = uri("https://jitpack.io") }
}

dependencies {
	implementation(libs.net.sf.cssbox.jstyleparser)	// Replace with jitpack
    implementation(libs.org.htmlunit.neko.htmlunit)
    implementation(libs.org.slf4j.slf4j.api)
    testImplementation(libs.junit.junit)
}

group = "net.sf.cssbox"
version = "5.0.3-SNAPSHOT"
description = "CSSBox"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
